"""
业务参数
"""
"""默认缓存时间 1分钟"""
REDIS_CACHE_TIME = 60
"""服务器redis key值"""
SERVER_CONFIG_REDIS_KEY = "server_config"
"""配置表"""
BUSI_BASE_CONF_REDIS_KEY = "busi_base_conf"
"""有效用户"""
VALID_ACCOUNT_REDIS_KEY = "valid_account"
"""锁定账户"""
LOCK_ACCOUNT_REDIS_KEY = "lock_account"
"""模板redis key值"""
TEMPLATE_REDIS_KEY = "template_config"
"""模板扩展redis key值"""
TEMPLATE_EXT_REDIS_KEY = "template_ext_config"
"""收取邮件保存地址"""
POP_BASE_PATH = "/AppData/edm/pop3/%s/%s/%s"
"""单批次最大发送量"""
BATCH_MAX_LENGTH = "busi_batch_max_length"
"""待发送邮箱域名"""
MARKETING_EMAIL_KEY = "busi_marketing_email_key"
"""筛选规则  1|1|1 0：不过滤 1：过滤"""
RESEND_RULES = "busi_resend_rules"
"""发送时间段"""
SEND_MIN_MAX_TIME = "busi_send_min_max_time"
"""重发最大次数"""
RE_SEND_MAX_LENGTH = "busi_re_send_max_length"
"""批次休眠时间"""
BUSI_BATCH_SLEEP_TIME = "busi_batch_sleep_time"
"""授权码"""
QUEUE_MANAGER_AUTH_KEY = "nozuonodiewhyyoutry"
"""绑定进程IP"""
QUEUE_MANAGER_ADDRESS = "106.12.140.232"
"""最大线程数"""
THREAD_MAX_WORKERS = "thread_max_workers"
"""消费者最大线程数"""
CONSUME_THREAD_MAX_WORKERS = "consume_thread_max_workers"
"""最大读取量"""
MAX_REDIS_READ_LENGTH = "max_redis_read_length"
"""消费者最大读取量"""
CONSUME_MAX_REDIS_READ_LENGTH = "consume_max_redis_read_length"

"""收取邮件休眠时间"""
COLLECT_SLEEP_TIME = "collect_sleep_time"
"""收取邮件账号间隔休眠时间"""
COLLECT_ACCOUNT_SLEEP_TIME = "collect_account_sleep_time"


"""生产休眠时间"""
PRODUCT_SLEEP_TIME = "product_sleep_time"
"""消费休眠时间"""
CONSUME_SLEEP_TIME = "consume_sleep_time"
"""账号休眠时间"""
ACCOUNT_SLEEP_TIME = "account_sleep_time"
"""再次启用间隔时间"""
ACCOUNT_REOPEN_TIME = "account_reopen_time"
"""是否开启黑名单"""
VERIFY_BLACK_ROLL_CALL = "verify_black_roll_call"
"""是否开启smtp账号校验"""
VERIFY_SEND_EMAIL_SMTP = "verify_send_email_smtp"
"""校验邮箱"""
VERIFY_EMAIL = "verify_email"
"""邮箱加密秘钥"""
SECRET_KEY = "adsawdws"
"""允许重发ip"""
ALLOW_RESEND_SERVER_IP = "allow_resend_server_ip"

"""任务文件基础地址"""
TASK_BASE_PATH = "/AppData/edm/task/%s/"






